fragment HeadingFragment on HeaderRecord {
  heading
  id
  navigationBar {
    id
    section
    heading
  }
  backgroundAnimation {
    url
    alt
    size
    height
    width
    title
    tags
  }
}

fragment AboutMeFragment on AboutMeRecord {
  title
  subtitle
  introText
  id
  displayName
  image {
    height
    width
    url
    title
    alt
  }
  meanings {
    heading
    id
    backgroundImage {
      alt
      url
      width
      height
    }
    meanings {
      description
      id
    }
  }
  profilePicture {
    width
    url
    title
    height
    alt
  }
}

fragment ExperienceFragment on TrainingBlockRecord {
  displayName
  id
  experience {
    year
    id
    event {
      title
      description
    }
    backgroundImage {
      url
      width
      height
      alt
    }
  }
}

fragment ServicesFragment on ServicesBlockRecord {
  title
  serviceList {
    name
    id
    description
    audioList {
      audio {
        url
        title
      }
      displayName
      language
    }
    animationImages {
      url
      title
      width
      height
    }
  }
  id
  basicContent {
    introText
    image {
      url
      title
      width
      height
    }
    id
    heading
    backgroundImages {
      image {
        url
        width
        title
        height
      }
      id
    }
  }
}

fragment ContactFragment on KontactBlockRecord {
  displayName
  basicContent {
    animation {
      url
      width
      title
      height
    }
    image {
      url
      width
      height
      alt
    }
    animation {
      url
    }
  }
}

query AudioList($locale: SiteLocale) {
  audioList(locale: $locale) {
    audio {
      language
      displayName
      audio {
        url
      }
      animationImages {
        url
      }
    }
  }
}

query AudioBlockAnimation($locale: SiteLocale) {
  audioList(locale: $locale) {
    images {
      url
      id
    }
    buttonAnimation {
      url
      id
    }
  }
}

query AboutMe($locale: SiteLocale) {
  aboutMe(locale: $locale) {
    ...AboutMeFragment
  }
}

query Experience($locale: SiteLocale) {
  trainingBlock(locale: $locale) {
    ...ExperienceFragment
  }
}

query Services($locale: SiteLocale) {
  servicesBlock(locale: $locale) {
    ...ServicesFragment
  }
}

query Contact($locale: SiteLocale) {
  kontactBlock(locale: $locale) {
    ...ContactFragment
  }
}

query Footer($locale: SiteLocale) {
  footer(locale: $locale) {
    title(locale: $locale)
    links(locale: $locale) {
      link
      id
      displayTitle
    }
    content(locale: $locale)
    backgroundImage {
      image {
        url
      }
    }
  }
}

query indexPage($locale: SiteLocale) {
  header(locale: $locale) {
    ...HeadingFragment
  }
}

query Header($locale: SiteLocale) {
  header(locale: $locale) {
    ...HeadingFragment
  }
}
